default: &default
  # adapter: sqlite3
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: lasha_development

test:
  <<: *default
  database: lasha_test

production:
  <<: *default
  # url: sqlite3://db/production.sqlite3
  database: lasha_production
