require: rubocop-performance

AllCops:
  Exclude:
    - "**/*.slim"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "db/*"
    - "db/fixtures/**/*"
    - "tmp/**/*"

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/FormatString:
  AutoCorrect: false

Metrics/LineLength:
  Max: 120
