source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
ruby "2.6.5"
gem "bootsnap", ">= 1.4.2", require: false
gem "jbuilder", "~> 2.7"
gem "pg", ">= 0.18", "< 2.0"
gem "puma", "~> 4.1"
gem "rails", "~> 6.0.2", ">= 6.0.2.2"
gem "turbolinks", "~> 5"
gem "webpacker", "~> 4.0"
group :development, :test do
  gem "byebug", platforms: %i[mri mingw x64_mingw]
end

group :development do
  gem "listen", ">= 3.0.5", "< 3.2"
  gem "web-console", ">= 3.3.0"
end

gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

################################################################################
gem "omniauth-bnet"

################################################################################
# General
gem "font-awesome-sass"
gem "lasha", path: "../lasha"
gem "meta-tags"
gem "notifications"
gem "oj"
gem "paper_trail"
gem "rest-client"
gem "simple_calendar", "~> 2.0"

# Services
gem "aws-sdk-s3", "~> 1"
gem "gravatar_image_tag"
gem "sendgrid-actionmailer"

# Security
# gem 'devise_masquerade'
# gem 'devise-two-factor'
# gem 'devise_token_auth', '~> 0.2'
# gem 'recaptcha'

# Debugging & Optimization
gem "active_record_query_trace"
gem "rack-utf8_sanitizer"

# I18n
gem "devise-i18n"
gem "rails-i18n"
# gem 'globalize', github: 'globalize/globalize'

# Mechanical Line
group :development, :test do
  gem "awesome_print"
  gem "bullet"
  gem "capybara"
  gem "database_cleaner"
  gem "dotenv-rails"
  gem "factory_bot_rails"
  gem "pry-rails"
  gem "rspec-rails"
  gem "webdrivers"
end

group :development, :test, :staging do
  gem "faker", "1.9.3"
end

group :development do
  gem "bcrypt_pbkdf"
  gem "capistrano", require: false
  gem "capistrano-bundler", require: false
  gem "capistrano-rails", require: false
  gem "capistrano-rvm", require: false
  gem "capistrano3-puma", require: false
  gem "derailed_benchmarks"
  gem "droplet_kit"
  gem "ed25519"
  gem "i18n-tasks", "~> 0.9.6"
  gem "i18n_generators", "~> 2.1", ">= 2.1.1"
  gem "rails-erd", require: false
  gem "rubocop"
  gem "rubocop-performance"
end
