---
:concurrency: 25

:queues:
  - default
  - mailers

  - dummy_app_development_default
  - dummy_app_development_mailers
  - dummy_app_development_active_storage_analysis

  - dummy_app_staging_default
  - dummy_app_staging_mailers
  - dummy_app_staging_active_storage_analysis

  - dummy_app_production_default
  - dummy_app_production_mailers
  - dummy_app_production_active_storage_analysis

  - scheduled_jobs

development:
  :verbose: true
  # :logfile: ./log/sidekiq.log

staging:
  :verbose: true
  :concurrency: 5

production:
