################ Sitemap ################
# Run sitemap generator everyday at 5:00 AM
sitemap_refresher:
  cron: "0 5 * * *"
  class: "SitemapWorker"
  queue: scheduled_jobs

################ Sitemap ################
# Run sitemap generator everyday at 5:00 AM
# day_end_closing:
#   cron: "0 5 * * *"
#   class: "DayEndClosingWorker"
#   queue: scheduled_jobs
