---
:concurrency: 25

:queues:
  - default
  - mailers

  - <%= Dir.pwd.split("/").last %>_development_default
  - <%= Dir.pwd.split("/").last %>_development_mailers
  - <%= Dir.pwd.split("/").last %>_development_active_storage_analysis

  - <%= Dir.pwd.split("/").last %>_staging_default
  - <%= Dir.pwd.split("/").last %>_staging_mailers
  - <%= Dir.pwd.split("/").last %>_staging_active_storage_analysis

  - <%= Dir.pwd.split("/").last %>_production_default
  - <%= Dir.pwd.split("/").last %>_production_mailers
  - <%= Dir.pwd.split("/").last %>_production_active_storage_analysis

  - scheduled_jobs

development:
  :verbose: true
  # :logfile: ./log/sidekiq.log

staging:
  :verbose: true
  :concurrency: 5

production:
