---
:concurrency: 25

:queues:
  - default
  - mailers

  - <%= ENV["RAILS_APP_NAME"] %>_<%= ENV["RAILS_ENV"] %>_default
  - <%= ENV["RAILS_APP_NAME"] %>_<%= ENV["RAILS_ENV"] %>_mailers
  - <%= ENV["RAILS_APP_NAME"] %>_<%= ENV["RAILS_ENV"] %>_active_storage_analysis

  - scheduled_jobs

development:
  :verbose: true
  # :logfile: ./log/sidekiq.log

staging:
  :verbose: true
  :concurrency: 5

production:
